### ISSUE TITLE
systemd user service startup as part of the ayatana-indicators.target

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/ayatana-indicator-messages#10]
@tari01: @mariogrip: do you see any blockers for adding systemd user service startup to the messages indicator, as well?

@mariogrip: Is the messages indicator used in Ubuntu Touch, at all?

**Comment by tari01** [comment]
It should work just fine. Messages are no different than other indicators in this respect.

**Comment by mariogrip** [comment]
This should also have a systemd file. Lomiri does indeed uses this.

I was planing to do it today, but seems like you got to it before me :)
