### ISSUE TITLE
Message menu items disabled

### ISSUE THREAD

**Issue by tari01** [AyatanaIndicators/ayatana-indicator-messages#3]
Version 0.6.0 on Arch + MATE integrates nicely, the indicator registers and shows the messaging application properly. When the client adds messages to the indicator, they show up, but the items are disabled and they do not show the time.

Tested with Unity Mail, Evoulution and the bundled client-example.py

**Comment by sunweaver** [comment]
Hi,

On Thursday, 7 March 2019, tari01 wrote:
> Version 0.6.0 on Arch + MATE integrates nicely, the indicator registers and shows the messaging application properly. When the client adds messages to the indicator, they show up, but the items are disabled and they do not show the time.
> 
> Tested with Unity Mail, Evoulution and the bundled client-example.py
> 

Thanks for this. Work on Ayatana Indicators has been stalled for a while, but I expect to be able to work on them with enforced manpower some time starting in April.

Meanwhile, I appreciate patch prosals.

Thanks+Greets,
Mike

-- 
Sent from my Sailfish device

**Comment by sunweaver** [comment]
@tari01: can you provide a test recipe? In fact, I noticed your unity-mail upstream project recently and I have bringing it to Debian on my list.

**Comment by sunweaver** [comment]
@tari01: I have limited time these days, so getting help with fixing this (and bringing this fix plus the fixes recently committed on master to Debian) will be highly appreciated.

**Comment by tari01** [comment]
> @tari01: can you provide a test recipe? In fact, I noticed your unity-mail upstream project recently and I have bringing it to Debian on my list.

I am not sure I can provide a proper test recipe that is both cross-distribution and cross-DE, I hope this quick list helps a bit, though. Anybody willing to replicate this issue get Manjaro MATE:

```
#Software settings
sudo sed -i "s@#EnableAUR@EnableAUR@" /etc/pamac.conf
sudo sed -i "s@#CheckAURUpdates@CheckAURUpdates@" /etc/pamac.conf
sudo sed -i "s@#CheckAURVCSUpdates@CheckAURVCSUpdates@" /etc/pamac.conf
pamac upgrade --aur

# Remove bundled indicator components
sudo pamac remove libappindicator-gtk3
sudo pamac remove libindicator-gtk3
sudo pamac remove ido

# Install Ayatana components
pamac build ayatana-ido
pamac build libayatana-indicator-gtk3
pamac build libayatana-appindicator-gtk3
pamac build ayatana-indicator-application
pamac build ayatana-indicator-power
pamac build ayatana-indicator-session
pamac build ayatana-indicator-messages
pamac build ayatana-indicator-datetime
pamac build mate-ayatana-indicator-applet

# Test application - works with all known indicator setups
pamac build unity-mail
```
NOTE: All the indicators that need to be installed are in the AUR, and maintained by me.

By the way, it seems my creations are bound to end up in your hands: short after I published caja-rename, it was you who discovered it and repackaged it into Debian :)

**Comment by khurshid-alam** [comment]
It works fine on Ubuntu 19.04. Though I believe it needs to be recompiled against newer libraries.

**Comment by sunweaver** [comment]
Hi,

On  Fr 22 Mär 2019 17:00:40 UTC, Khurshid Alam wrote:

> It works fine on Ubuntu 19.04. Though I believe it needs to be  
> recompiled against newer libraries.

You have to make sure you have libmessaging-menu from  
ayatana-indicator-messages. Ubuntu, by default, has indicator-messages.

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by tari01** [comment]
I am closing this because the problem is really in **ayatana-ido** not being able to build custom **GMenu** items.
