### ISSUE TITLE
libmessaging-menu0,  gir1.2-messagingmenu-1.0 naming collides with indicator-messages ?

### ISSUE THREAD

**Issue by khurshid-alam** [AyatanaIndicators/ayatana-indicator-messages#37]
In indicator-messages on [Ubuntu](https://launchpad.net/ubuntu/+source/indicator-messages/13.10.1+18.10.20180918-0ubuntu5), the changelog says,

```
  * debian/conrol, debian/*.install: drop the libmessaging-menu0,
    libmessaging-menu-dev and gir1.2-messagingmenu-1.0 binary packages. Those
    are built and provided by ayatana-indicator-messages and cannot
    realistically be published to the archive during builds right now. 
```

But if a application compiled with libmessaging-menu-dev  or gir1.2-messagingmenu-1.0 for python app will it actually work it indicator-messages ? I see there are there no changes in so names. 

**In my testing it doesn't work with pidgin or any app that uses libmessaging-menu0**

Unity still uses indicator-messages. Porting to ayatana hasn't happened yet. It it doesn't work wouldn't it better ti rename those as `libayatana-messaging-menu0` ?

**Comment by tari01** [comment]
I am going to answer part of your question: `ayatana-indicator-messages` has indeed replaced the old `indicator-messages` despite the fact that it provides the same library names. The library and language bindings work. For a Python reference, see the [Ayatana Webmail](https://github.com/AyatanaIndicators/ayatana-webmail/blob/8b408af677090ccaf23aa03e5e90d5a26ef71ac9/ayatanawebmail/application.py#L132) application.

For the record, I agree with you regarding the name change (`libayatana-messaging` would make a lot more sense). 

About the why and how of Debian packaging, you will need to ask @sunweaver. Please tell me if this answer is satisfactory so I could close this issue.

**Comment by sunweaver** [comment]
> In indicator-messages on [Ubuntu](https://launchpad.net/ubuntu/+source/indicator-messages/13.10.1+18.10.20180918-0ubuntu5), the changelog says,
> 
> ```
>   * debian/conrol, debian/*.install: drop the libmessaging-menu0,
>     libmessaging-menu-dev and gir1.2-messagingmenu-1.0 binary packages. Those
>     are built and provided by ayatana-indicator-messages and cannot
>     realistically be published to the archive during builds right now. 
> ```
> 
> But if a application compiled with libmessaging-menu-dev or gir1.2-messagingmenu-1.0 for python app will it actually work it indicator-messages ? I see there are there no changes in so names.
> 
> **In my testing it doesn't work with pidgin or any app that uses libmessaging-menu0**
> 
> Unity still uses indicator-messages. Porting to ayatana hasn't happened yet. It it doesn't work wouldn't it better ti rename those as `libayatana-messaging-menu0` ?

To my understanding, all of Ubuntu (except from Unity7) has switched to Ayatana Indicators these days. We chose the libmessaging-menu package name to make the ayatana-indicator-messages client API library a drop-in replacement for all consumers in Ubuntu.

Please encourage Unity7 maintainers to bump to Ayatana Indicators. Even Ubuntu Touch has moved over to Ayatana Indicators. While Ubuntu Indicators are scarcely maintained these days, Ayatana Indicators see active development and feature enrichment. 

We are very open to Unity7 developers porting over their environment to Ayatana Indicators (it is, in fact, the last piece of the puzzle to complete the transition). If people start working on this transition we will be happy to help and accept pull requests here.

Closing this issue, as we will not rename the library package for now.

**Comment by khurshid-alam** [comment]
@sunweaver I think porting to ayatana indicators and renaming the library are two different things. Unity has many components where indicators are being used so porting was not easy as we are very few active member working on those components.
